project:
  type: website
  
website:
  title: "Wave Data Labs"
  site-url: "https://wavedatalabs.com.au"
  description: "Data Science and Statistical Consulting"
  favicon: img/logo.png
  open-graph: true
  google-analytics: "UA-XXXXXXXX"
  navbar:
    logo: img/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: services/index.qmd  
        text: Services
      - href: about/index.qmd
        text: Team
      - href: contact/index.qmd
        text: Contact
  page-footer:
    background: "#FF000000"
    center:
      - text: "Copyright 2024, Wave Data Labs Pty Ltd."
        href: index.qmd
  
format:
  html:
    theme: 
      dark: [solar, theme-dark.scss]
      light: cosmo
    css: styles.css
    toc: false


